version: '3.7'

services:
  postgres:
    image: postgres:latest
    ports:
      - '5433:5432'
    environment:
      - POSTGRES_USER=my-postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - postgres_pg_data:/postgres


volumes:
  - postgres_pg_data